version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_engineering_blog_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_engineering_blog_net
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_HOST=mysql
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    mysql:
        image: mysql:8.0
        container_name: laravel_engineering_blog_mysql_db
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel_engineering_blog_net

    nginx:
        image: nginx:alpine
        container_name: laravel_engineering_blog_nginx_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_engineering_blog_net

networks:
    laravel_engineering_blog_net:

volumes:
    dbdata:
